//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloginfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bloginfo()
        {
            this.blogcontents = new HashSet<blogcontent>();
        }
    
        public int BlogId { get; set; }
        public string Title { get; set; }
        public System.DateTime PostDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Tags { get; set; }
        public bool IsActive { get; set; }
        public int BloggerId { get; set; }
    
        public virtual blogger blogger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogcontent> blogcontents { get; set; }
    }
}
