//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    
    public partial class blog_category
    {
        public string Name { get; set; }
        public DateTime? DateCreated { get; set; }
        public int TaggedBlogCount { get; set; }
    }
}
