//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class instagram
    {
        public string Id { get; set; }
        public string Media_Url { get; set; }
        public string Caption { get; set; }
        public string Media_Type { get; set; }
        public DateTime? Timestamp { get; set; }
        public string Permalink { get; set; }
        public string Thumbnail_Url { get; set; }
    }
}
