//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyTravelBlogEntities : DbContext
    {
        public MyTravelBlogEntities()
            : base("name=MyTravelBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blogger> bloggers { get; set; }
        public virtual DbSet<bloginfo> bloginfoes { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<postcontent> postcontents { get; set; }
        public virtual DbSet<role> roles { get; set; }
    }
}
