//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    
    public partial class newsletter_sub
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public bool? IsSubscribed { get; set; }
        public DateTime? SubscribedDate { get; set; }
        public DateTime? Un_SubscribedDate { get; set; }
    }
}
