//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postcontent
    {
        public int Id { get; set; }
        public string Intro_Highlight { get; set; }
        public string Introduction { get; set; }
        public string Quote { get; set; }
        public string Description_Start { get; set; }
        public string Image_BeforeHighlights { get; set; }
        public string ImageStartAlt { get; set; }
        public string Highlights { get; set; }
        public string Image_AfterHighlights { get; set; }
        public string ImageUpperMidAlt { get; set; }
        public string Description_End { get; set; }
        public string Image_End { get; set; }
        public string ImageLowerMidAlt { get; set; }
        public string Closing_Statements { get; set; }
        public string Image_Direction { get; set; }
        public string ImageDirectionAlt { get; set; }
        public string Direction { get; set; }
        public string ArrivingHere { get; set; }
        public string Attractions { get; set; }
        public string Accommodation { get; set; }
    }
}
